services:
  - type: web
    name: profiremanager-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SUPER_ADMIN_EMAIL
        value: gussdub@icloud.com
    healthCheckPath: /api/health
